name: "Tests Pytest on Tag"

on:
  push:
    # déclenchement uniquement si on pousse un tag vX.Y.Z
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run Pytest
        run: pytest -q
